name: ChurnBuster CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKOPHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t salma003/churnbuster-api:latest .

      - name: Push Docker image
        run: docker push salma003/churnbuster-api:latest